In [11]:
from pathlib import Path

import pandas as pd

In [ ]:
data_path = Path("data/data_pandas_practice.csv")
if not data_path.exists():
    data_path = Path("../data/data_pandas_practice.csv")

read = pd.read_csv(data_path)

# pd.read_csv(...) reads the CSV file and returns a pandas DataFrame

In [13]:
print(read)

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

### DataFrame vs Series
#### DataFrame: Full 2D table (Excel spreadsheet)
#### Series: Single column (One column from that spreadsheet)

In [14]:
# Creating a DataFrame
data = {
    'Name':  ['Alice', 'Bob', 'Carol', 'Dave'],
    'Score': [85, 92, 78, 95],
    'Grade': ['B', 'A', 'C', 'A']
}

# print(data)

df = pd.DataFrame(data)
print(df)

    Name  Score Grade
0  Alice     85     B
1    Bob     92     A
2  Carol     78     C
3   Dave     95     A

In [ ]:
# Creating a series
s = df['Score'] #single column of the data frame
print(s)
print(type(s))

0    85
1    92
2    78
3    95
Name: Score, dtype: int64
<class 'pandas.Series'>

#### df.head()        # first 5 rows - quick preview
#### df.shape         # (rows, columns) - e.g. (1000, 12)
#### df.info()        # column names, data types, missing count
#### df.describe()    # mean, min, max, std for numeric columns

In [19]:
data2 = {
    'Name':       ['Alice', 'Bob', 'Carol', 'Dave', 'Eve', 'Frank', 'Grace', 'Hank'],
    'Age':        [22, 25, 23, 28, 21, 26, 24, 27],
    'Score':      [85, 92, 78, 95, 88, 73, 90, 81],
    'Grade':      ['B', 'A', 'C', 'A', 'B', 'C', 'A', 'B'],
    'Attendance': [91, 85, 78, 96, 88, 70, 93, 82],
    'Subject':    ['Math', 'Science', 'English', 'Math', 'Science', 'English', 'Math', 'Science'],
    'Passed':     [True, True, False, True, True, False, True, True]
}

dataFrm = pd.DataFrame(data2)

In [24]:
print(dataFrm)
print("     -----------------------------------------------")
dataFrm.head()

    Name  Age  Score Grade  Attendance  Subject  Passed
0  Alice   22     85     B          91     Math    True
1    Bob   25     92     A          85  Science    True
2  Carol   23     78     C          78  English   False
3   Dave   28     95     A          96     Math    True
4    Eve   21     88     B          88  Science    True
5  Frank   26     73     C          70  English   False
6  Grace   24     90     A          93     Math    True
7   Hank   27     81     B          82  Science    True
     -----------------------------------------------

    Name  Age  Score Grade  Attendance  Subject  Passed
0  Alice   22     85     B          91     Math    True
1    Bob   25     92     A          85  Science    True
2  Carol   23     78     C          78  English   False
3   Dave   28     95     A          96     Math    True
4    Eve   21     88     B          88  Science    True

In [26]:
dataFrm.shape

(8, 7)

In [27]:
dataFrm.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        8 non-null      str
 1   Age         8 non-null      int64
 2   Score       8 non-null      int64
 3   Grade       8 non-null      str
 4   Attendance  8 non-null      int64
 5   Subject     8 non-null      str
 6   Passed      8 non-null      bool
dtypes: bool(1), int64(3), str(3)
memory usage: 524.0 bytes

In [29]:
dataFrm.describe()

            Age      Score  Attendance
count   8.00000   8.000000    8.000000
mean   24.50000  85.250000   85.375000
std     2.44949   7.478541    8.551316
min    21.00000  73.000000   70.000000
25%    22.75000  80.250000   81.000000
50%    24.50000  86.500000   86.500000
75%    26.25000  90.500000   91.500000
max    28.00000  95.000000   96.000000

### One column -> Series (single brackets)
#### df['Name']

### Multiple columns -> DataFrame (double brackets)
#### df[['Name', 'Score']]

In [31]:
dataFrm['Name']

0    Alice
1      Bob
2    Carol
3     Dave
4      Eve
5    Frank
6    Grace
7     Hank
Name: Name, dtype: str

In [33]:
dataFrm[['Name', 'Score','Age']]

    Name  Score  Age
0  Alice     85   22
1    Bob     92   25
2  Carol     78   23
3   Dave     95   28
4    Eve     88   21
5  Frank     73   26
6  Grace     90   24
7   Hank     81   27

#### .loc[]  -> by LABEL (name of the index)
##### df.loc[0]               # row with index label 0
##### df.loc[0, 'Name']       # row 0, column 'Name' -> 'Alice'
##### df.loc[0:2]             # rows 0, 1, 2 (INCLUSIVE)

#### .iloc[] -> by POSITION (like a Python list)
##### df.iloc[0]              # first row
##### df.iloc[0, 1]           # row 0, column position 1 -> 85
##### df.iloc[0:2]            # rows 0, 1 only (EXCLUSIVE)

In [2]:
# .loc[]

# dataFrm.loc[0]
# dataFrm.loc[0, 'Name']
# dataFrm.loc[0:2]

In [ ]:
#iloc[]

# dataFrm.iloc[0]
# dataFrm.iloc[0, 1] #return datatype
# int(dataFrm.iloc[0, 1]) #show data
# dataFrm.iloc[0:2]

    Name  Age  Score Grade  Attendance  Subject  Passed
0  Alice   22     85     B          91     Math    True
1    Bob   25     92     A          85  Science    True

In [ ]:
# Keep only rows where Score > 90
# df[df['Score'] > 90]

# AND condition - both must be true
# df[(df['Score'] > 80) & (df['Grade'] == 'A')]

# OR condition - at least one true
# df[(df['Score'] < 80) | (df['Score'] > 90)]

# # .isin() - match a list of values
# df[df['Grade'].isin(['A', 'B'])]

    Name  Score Grade
0  Alice     85     B
1    Bob     92     A
3   Dave     95     A

In [55]:
# Sort by Score (highest first)
# df = df.sort_values('Score', ascending=False)

# Rename columns
# df = df.rename(columns={'Name': 'Student', 'Score': 'Marks'})

# After filtering, index becomes messy (0, 2, 3...)
# reset_index fixes it back to 0, 1, 2...
df = df.reset_index(drop=True)

In [56]:
print(df)

  Student  Marks Grade
0    Dave     95     A
1     Bob     92     A
2   Alice     85     B
3   Carol     78     C

In [73]:
import numpy as np
thisData = {
    'Name':  ['Alice', 'Bob', 'Carol', 'Dave', 'Eve'],
    'Score': [85, np.nan, 78, 95, np.nan],
    'Grade': ['B', 'A', None, 'A', 'B']
}

newData = pd.DataFrame(thisData)
print(newData)

    Name  Score Grade
0  Alice   85.0     B
1    Bob    NaN     A
2  Carol   78.0   NaN
3   Dave   95.0     A
4    Eve    NaN     B

In [ ]:
# newData.isna().sum()          # count missing values per column
# newData.dropna()              # remove rows with ANY missing value
# newData.dropna(subset=['Score'])  # remove only if Score is missing

# newData.fillna(0)                          # Fill ALL missing with 0
newData['Grade'] = newData['Grade'].fillna('NA')
newData['Score'] = newData['Score'].fillna(newData['Score'].mean()) # fill with mean (common in ML)

In [93]:
print(newData)

    Name  Score Grade
0  Alice   85.0     B
1    Bob   86.0     A
2  Carol   78.0    NA
3   Dave   95.0     A
4    Eve   86.0     B

In [97]:
# newData['Grade'].value_counts()   # how many A, B, C...
# A    2
# B    1
# C    1

# newData['Grade'].unique()         # ['B', 'A', 'C']  - what values exist
newData['Grade'].nunique()        # 3  - how many distinct values

3